# Generated by Django 5.2 on 2025-06-06 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cultural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('barrio', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('fechaPublicacion', models.DateTimeField(auto_now_add=True)),
                ('reseña', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Diseño',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('barrio', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('fechaPublicacion', models.DateTimeField(auto_now_add=True)),
                ('reseña', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Gastronomia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('barrio', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('fechaPublicacion', models.DateTimeField(auto_now_add=True)),
                ('reseña', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Nocturno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('barrio', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('fechaPublicacion', models.DateTimeField(auto_now_add=True)),
                ('reseña', models.CharField(max_length=1000)),
            ],
        ),
    ]
