# Generated by Django 5.2 on 2025-06-12 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppRubros', '0003_alter_avatar_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cultural',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_locales/'),
        ),
        migrations.AddField(
            model_name='diseño',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_locales/'),
        ),
        migrations.AddField(
            model_name='gastronomia',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_locales/'),
        ),
        migrations.AddField(
            model_name='nocturno',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_locales/'),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
